import { GAME_WIDTH as W, GAME_HEIGHT as H, WORLD_WIDTH, LEVEL_FLOOR } from './config/gameConfig.js';
import { beep } from './audio/sound.js';
import { rectsOverlap as rect } from './systems/collision.js';

const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;document.getElementById('game').append(canvas);const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;document.body.style='margin:0;background:#101525;display:grid;place-items:center;height:100vh;';canvas.style='width:min(100vw,177vh);height:auto;image-rendering:pixelated';
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);
const down=(...c)=>c.some(x=>keys[x]);let mode='menu',cam=0,score=0,bullets=[],ebullets=[],enemies=[],pickups=[],plats=[],boss=null,paused=false,last=0;
const player={x:48,y:120,w:14,h:18,vx:0,vy:0,hp:5,max:5,lives:3,inv:0,face:1,state:'idle',power:0,on:false};
function reset(){score=0;cam=0;bullets=[];ebullets=[];enemies=[];pickups=[];boss=null;Object.assign(player,{x:48,y:120,vx:0,vy:0,hp:5,lives:3,inv:0,power:0});plats=[];for(let x=0;x<WORLD_WIDTH;x+=16)plats.push({x,y:LEVEL_FLOOR,w:16,h:32});[[360,145,128],[620,118,96],[900,150,112],[1250,118,80],[1570,142,112],[1900,108,128],[2230,145,80],[2650,130,112],[3100,150,208]].forEach(p=>plats.push({x:p[0],y:p[1],w:p[2],h:12}));[[260,150,'patrol'],[540,96,'gunner'],[790,90,'fly'],[1080,150,'patrol'],[1380,96,'fly'],[1650,120,'gunner'],[1830,150,'patrol'],[2060,80,'fly'],[2350,150,'gunner'],[2550,150,'patrol']].forEach(([x,y,t])=>enemies.push({x,y,w:16,h:16,type:t,hp:t==='gunner'?3:2,dir:-1,base:x,cd:900}));[[700,92,'health'],[1500,100,'power'],[2200,108,'health'],[2860,105,'power']].forEach(([x,y,t])=>pickups.push({x,y,w:10,h:10,type:t}));}
function start(){reset();mode='game';beep(660,.1)}function shoot(){if(player.cd>0)return;player.cd=player.power>0?9:16;let dx=player.face,dy=0;if(down('KeyW','ArrowUp'))dy=-1;if(down('KeyS','ArrowDown')&&!player.on)dy=1;if(down('KeyW','ArrowUp')&&(down('KeyA','ArrowLeft')||down('KeyD','ArrowRight')))dx=down('KeyA','ArrowLeft')?-1:1;let l=Math.hypot(dx,dy)||1;bullets.push({x:player.x+8,y:player.y+7,w:player.power>0?7:4,h:3,vx:dx/l*(player.power>0?250:210),vy:dy/l*(player.power>0?250:210),d:player.power>0?2:1});beep(360,.04)}
function hurt(d=1){if(player.inv>0)return;player.hp-=d;player.inv=80;beep(110,.12);if(player.hp<=0){player.lives--;if(player.lives<0){mode='lose';beep(70,.4)}else{player.hp=player.max;player.x=Math.max(48,boss?2700:48);player.y=120}}}
function update(dt){if(down('Escape')){paused=!paused;keys.Escape=false}if(paused)return;player.cd--;player.inv--;player.power--;let left=down('KeyA','ArrowLeft'),right=down('KeyD','ArrowRight');player.vx=(right-left)*105;if(player.vx)player.face=Math.sign(player.vx);if(down('Space')&&player.on){player.vy=-285;beep(520,.05)}if(down('KeyJ','KeyZ'))shoot();player.vy+=720*dt;player.x+=player.vx*dt;player.y+=player.vy*dt;player.on=false;for(const p of plats)if(rect(player,p)&&player.vy>=0&&player.y+player.h-p.y<18){player.y=p.y-player.h;player.vy=0;player.on=true}if(player.y>240)hurt(99);player.state=!player.on?'jump':Math.abs(player.vx)>5?'run':'idle';cam=Math.max(0,Math.min(WORLD_WIDTH-W,player.x-110));
for(const e of enemies){if(e.type==='patrol'){e.x+=e.dir*45*dt;if(Math.abs(e.x-e.base)>70)e.dir*=-1;if(Math.abs(player.x-e.x)<45)e.x+=Math.sign(player.x-e.x)*45*dt}else if(e.type==='gunner'){e.cd-=dt*1000;if(e.cd<0){e.cd=1500;ebullets.push({x:e.x,y:e.y+6,w:6,h:5,vx:Math.sign(player.x-e.x)*120,vy:0,d:1});beep(220,.04)}}else{e.x+=Math.sin(performance.now()/360+e.base)*.35;e.y+=Math.sin(performance.now()/220+e.base)*.55;if(Math.abs(player.x-e.x)<120){let a=Math.atan2(player.y-e.y,player.x-e.x);e.x+=Math.cos(a)*50*dt;e.y+=Math.sin(a)*50*dt}}if(rect(player,e))hurt(e.type==='fly'?1:1)}
if(player.x>2740&&!boss){boss={x:3340,y:140,w:44,h:42,hp:40,max:40,cd:1200,phase:1,warn:0};beep(90,.4)}if(boss){boss.phase=boss.hp<20?2:1;boss.y=140+Math.sin(performance.now()/450)*8;boss.cd-=dt*1000;if(boss.cd<300)boss.warn=1;if(boss.cd<=0){boss.warn=0;boss.cd=boss.phase===2?850:1300;let n=boss.phase===2?5:3;for(let i=0;i<n;i++){let a=Math.atan2(player.y-boss.y,player.x-boss.x)+(i-(n-1)/2)*.22;ebullets.push({x:boss.x,y:boss.y+18,w:6,h:5,vx:Math.cos(a)*125,vy:Math.sin(a)*125,d:1})}if(boss.phase===2)enemies.push({x:boss.x-70,y:105,w:16,h:16,type:'fly',hp:1,dir:-1,base:boss.x-70,cd:0})}if(rect(player,boss))hurt(2)}
for(const arr of [bullets,ebullets])for(const b of arr){b.x+=b.vx*dt;b.y+=b.vy*dt}for(const b of bullets){for(const e of enemies)if(!e.dead&&rect(b,e)){b.dead=true;e.hp-=b.d;if(e.hp<=0){e.dead=true;score+=e.type==='fly'?180:100;beep(240,.08)}}if(boss&&rect(b,boss)){b.dead=true;boss.hp-=b.d;if(boss.hp<=0){score+=2500;mode='win';beep(880,.35)}}}for(const b of ebullets)if(rect(player,b)){b.dead=true;hurt(b.d)}for(const p of pickups)if(!p.dead&&rect(player,p)){p.dead=true;score+=50;if(p.type==='power')player.power=720;else player.hp=Math.min(player.max,player.hp+2);beep(760,.07)}bullets=bullets.filter(b=>!b.dead&&b.x>cam-80&&b.x<cam+480&&b.y>-40&&b.y<260);ebullets=ebullets.filter(b=>!b.dead&&b.x>cam-80&&b.x<cam+480);enemies=enemies.filter(e=>!e.dead);pickups=pickups.filter(p=>!p.dead)}
function drawChicken(x,y,c,gun=true){ctx.fillStyle=c;ctx.fillRect(x+4,y+4,12,12);ctx.fillStyle='#e83b3b';ctx.fillRect(x+3,y+2,14,3);ctx.fillStyle='#ffd35a';ctx.fillRect(x+15,y+8,5,4);ctx.fillStyle='#222';ctx.fillRect(x+11,y+7,2,2);if(gun){ctx.fillStyle='#6b4a2b';ctx.fillRect(x+12,y+13,10,3)}}
function render(){ctx.fillStyle='#1b2340';ctx.fillRect(0,0,W,H);for(let i=0;i<22;i++){ctx.fillStyle='#263b45';ctx.fillRect(i*220-cam*.35,150,120,42);ctx.fillStyle='#314e55';ctx.fillRect(i*220+45-cam*.55,92,34,58)}ctx.save();ctx.translate(-cam,0);ctx.fillStyle='#6b4a2b';plats.forEach(p=>{ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#9b6b32';ctx.fillRect(p.x,p.y,p.w,4);ctx.fillStyle='#6b4a2b'});pickups.forEach(p=>{ctx.fillStyle=p.type==='power'?'#ffdf47':'#ff4f6d';ctx.fillRect(p.x,p.y,p.w,p.h)});enemies.forEach(e=>drawChicken(e.x,e.y,e.type==='gunner'?'#7a8b48':e.type==='fly'?'#ce7f4b':'#c85d4d',e.type!=='fly'));if(boss){ctx.fillStyle=boss.warn?'#ffee55':'#43506d';ctx.fillRect(boss.x,boss.y,boss.w,boss.h);ctx.fillStyle='#ff3d57';ctx.fillRect(boss.x+32,boss.y+14,10,8);ctx.fillStyle='#111';ctx.fillRect(boss.x-8,boss.y+24,14,6)}ctx.globalAlpha=player.inv>0&&Math.floor(player.inv/5)%2?.45:1;drawChicken(player.x,player.y,'#f6e6b0');ctx.globalAlpha=1;ctx.fillStyle='#ffe08a';bullets.forEach(b=>ctx.fillRect(b.x,b.y,b.w,b.h));ctx.fillStyle='#fff2d6';ebullets.forEach(b=>ctx.fillRect(b.x,b.y,b.w,b.h));ctx.restore();ctx.fillStyle='white';ctx.font='8px monospace';ctx.fillText(`VIDA ${player.hp}/${player.max} VIDAS ${player.lives} PUNTOS ${score}`,8,12);if(boss){ctx.fillStyle='#200c18';ctx.fillRect(115,16,154,8);ctx.fillStyle='#ff3d57';ctx.fillRect(117,18,150*(boss.hp/boss.max),4)}if(paused)center('PAUSA',92,'#ffdf66');}
function center(t,y,c='white'){ctx.fillStyle=c;ctx.font='16px monospace';ctx.textAlign='center';ctx.fillText(t,W/2,y);ctx.textAlign='left'}function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(mode==='game')update(dt);render();if(mode==='menu'){center('SHOOTER POLLOS',70,'#ffdf66');ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText('ENTER empezar - pollo run-and-gun original',W/2,100);if(down('Enter'))start()}if(mode==='win'||mode==='lose'){center(mode==='win'?'¡VICTORIA AVÍCOLA!':'DERROTA EN EL CORRAL',78,mode==='win'?'#8cff8c':'#ff6b6b');ctx.font='10px monospace';ctx.textAlign='center';ctx.fillText(`Puntos: ${score}  ENTER reinicia`,W/2,108);if(down('Enter'))start()}requestAnimationFrame(loop)}reset();requestAnimationFrame(loop);
